//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileWatcherService.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\WORK\\log\\Incremental")]
        public string watchDir {
            get {
                return ((string)(this["watchDir"]));
            }
            set {
                this["watchDir"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("To123.log")]
        public string watchFilter {
            get {
                return ((string)(this["watchFilter"]));
            }
            set {
                this["watchFilter"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Services\\FileWatcherService\\FileWatcherService\\bin" +
            "\\Debug\\metrics.xml")]
        public string metricsFilePath {
            get {
                return ((string)(this["metricsFilePath"]));
            }
            set {
                this["metricsFilePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\zabbix_agents\\3.2.0\\bin\\win64\\zabbix_sender.exe ")]
        public string zabbixSenderPath {
            get {
                return ((string)(this["zabbixSenderPath"]));
            }
            set {
                this["zabbixSenderPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string zabbixServer {
            get {
                return ((string)(this["zabbixServer"]));
            }
            set {
                this["zabbixServer"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LOCALHOST.PROCESSES")]
        public string zabbixNetworkNode {
            get {
                return ((string)(this["zabbixNetworkNode"]));
            }
            set {
                this["zabbixNetworkNode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool zabbixEnableSend {
            get {
                return ((bool)(this["zabbixEnableSend"]));
            }
            set {
                this["zabbixEnableSend"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("err(or)?")]
        public string regexpError {
            get {
                return ((string)(this["regexpError"]));
            }
            set {
                this["regexpError"] = value;
            }
        }
    }
}
